12391     1 output/observeFail.py.err
00000     0 output/observeFail.py.out
